# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install MyPy types
      run: |
        if [ -f requirements_mypy.txt ]; then pip install -r requirements_mypy.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 jira_analysis/ --count --show-source --statistics
    - name: Lint tests
      run: |
        flake8 test/ --count --show-source --extend-ignore=F811,F401
    - name: Validate with mypy
      run: |
        mypy --strict jira_analysis/*
    - name: Test with pytest
      run: |
        pytest test/
